<!DOCTYPE HTML PUBLIC "-//W3O//DTD W3 HTML 2.0//EN">

<HTML>
<HEAD>
<TITLE>ICS 1C HW 4</TITLE>
<!-- Revised February 1995, ics1c@ics.uci.edu
     Be sure to Keep Current these comments
-->
</HEAD>

<BODY>

<A NAME="TOP">
<H1>ICS 1C HW 4</H1></a>

<FORM METHOD=POST ACTION="http://www.oac.uci.edu/cgi-bin/zd.cgi">
<INPUT TYPE=hidden NAME=ZD-Date-Format VALUE="%B %d, %Y">
<INPUT TYPE=hidden NAME=name1 VALUE="Name 1 NotEntered">
<INPUT TYPE=hidden NAME=name2 VALUE="Name 2 NotEntered">
<INPUT TYPE=hidden NAME=name3 VALUE="Name 3 NotEntered">
<INPUT TYPE=hidden NAME=name4 VALUE="Name 4 NotEntered">
<INPUT TYPE=hidden NAME=name5 VALUE="Name 5 NotEntered">
<INPUT TYPE=hidden NAME=EMAIL1 VALUE="eaxx123">
<INPUT TYPE=hidden NAME=EMAIL2 VALUE="eaxx123">
<INPUT TYPE=hidden NAME=EMAIL3 VALUE="eaxx123">
<INPUT TYPE=hidden NAME=EMAIL4 VALUE="eaxx123">
<INPUT TYPE=hidden NAME=EMAIL5 VALUE="eaxx123">
<INPUT TYPE=hidden NAME=URL1 VALUE="URL 1 NotEntered">
<INPUT TYPE=hidden NAME=URL2 VALUE="URL 2 NotEntered">
<INPUT TYPE=hidden NAME=URL3 VALUE="URL 3 NotEntered">
<INPUT TYPE=hidden NAME=URL4 VALUE="URL 4 NotEntered">
<INPUT TYPE=hidden NAME=URL5 VALUE="URL 5 NotEntered">
<INPUT TYPE=hidden NAME=DESC1 VALUE="Description 1 NotEntered">
<INPUT TYPE=hidden NAME=DESC2 VALUE="Description 2 NotEntered">
<INPUT TYPE=hidden NAME=DESC3 VALUE="Description 3 NotEntered">
<INPUT TYPE=hidden NAME=DESC4 VALUE="Description 4 NotEntered">
<INPUT TYPE=hidden NAME=DESC5 VALUE="Description 5 NotEntered">
<INPUT TYPE=hidden NAME=proposal VALUE="Proposal NotEntered">

<h2>General Instructions</h2>


As part of <!--A HREF="http://www.ics.uci.edu/~ics1c/doc/assignment-4.html">
UCI ICS 1C, Lab Exercise 4</A>, complete and submit this form during
labs on Wednesday and Thursday, March 1 and 2, 1995.
<p>
You fill in the form by typing the information requested in
each of the areas given below.
Instructions on ``submitting'' your responses are given at the end
of this document.
<h2>Team Member's Identification Information</h2>
Projects can be done individually or by a team of up to 4 members.
<p>
<B>Team Member 1:</B>
<INPUT TYPE=text SIZE=30 NAME=name1><br>
E-mail: <INPUT TYPE=TEXT SIZE=8 NAME=EMAIL1><code>@ea.oac.uci.edu</code><br>

<B>Team Member 2:</B>
<INPUT TYPE=text SIZE=30 NAME=name2><br>
E-mail: <INPUT TYPE=TEXT SIZE=8 NAME=EMAIL2><code>@ea.oac.uci.edu</code><br>

<B>Team Member 3:</B>
<INPUT TYPE=text SIZE=30 NAME=name3><br>
E-mail: <INPUT TYPE=TEXT SIZE=8 NAME=EMAIL3><code>@ea.oac.uci.edu</code><br>

<B>Team Member 4:</B>
<INPUT TYPE=text SIZE=30 NAME=name4><br>
E-mail: <INPUT TYPE=TEXT SIZE=8 NAME=EMAIL4><code>@ea.oac.uci.edu</code><br>

<HR>

<h2>Five distinct sites you've found</H2>
<OL>
<LI>
URL of the first distinct site you found:<BR>
<INPUT TYPE=text SIZE=60 NAME="URL1"><BR>
Short description of this site:
<TEXTAREA ROWS=2 COLS=60 NAME="DESC1"></TEXTAREA><BR>

<LI>
URL of the second distinct site you found:<BR>
<INPUT TYPE=text SIZE=60 NAME="URL2"><BR>
Short description of this site:
<TEXTAREA ROWS=2 COLS=60 NAME="DESC2"></TEXTAREA><BR>

<LI>
URL of the third distinct site you found:<BR>
<INPUT TYPE=text SIZE=60 NAME="URL3"><BR>
Short description of this site:
<TEXTAREA ROWS=2 COLS=60 NAME="DESC3"></TEXTAREA><BR>

<LI>
URL of the fourth distinct site you found:<BR>
<INPUT TYPE=text SIZE=60 NAME="URL4"><BR>
Short description of this site:
<TEXTAREA ROWS=2 COLS=60 NAME="DESC4"></TEXTAREA><BR>

<LI>
URL of the fifth distinct site you found:<BR>
<INPUT TYPE=text SIZE=60 NAME="URL5"><BR>
Short description of this site:
<TEXTAREA ROWS=2 COLS=60 NAME="DESC5"></TEXTAREA><BR>

</OL>

<H2>Proposal</H2>
<TEXTAREA ROWS=12 COLS=64 NAME=proposal></TEXTAREA>

<hr>

<I>After selecting one of the options below,
press the <b>Do It!</B> button to perform the indicated action.
<br>
The first option allows you to preview what you are submitting.
Use the ``Back'' button on your browser to get back to the form.
<br>
When you are ready to actually submit what you have typed in
to the ICS 1C Instructional Staff, select the second option
(``Submit the information on this form via mail to
<CODE>ics1c@ics.uci.edu</CODE>'') and press the
<b>Do It!</B> button.  The information will be mailed automatically.
</I>

<INPUT TYPE=hidden NAME=ZD-Method VALUE="ZD-Reflect;;body:
&lt;TITLE&gt;Successful Submission&lt;/TITLE&gt;
&lt;H1&gt;Successful Submission&lt;/H1&gt;
Your information has been e-mailed to &lt;CODE&gt;ics1c@ics.uci.edu&lt;/CODE&gt;.
">

<P><INPUT TYPE=radio NAME=ZD-Method 
VALUE="ZD-Reflect;;http://www.ics.uci.edu/~ics1c/doc/hw4a.temp" CHECKED>
	Preview the way your document would look<BR> 
<INPUT TYPE=radio NAME=ZD-Method
VALUE="ZD-Mail;ics1c@ics.uci.edu;http://www.ics.uci.edu/~ics1c/doc/hw4a.temp">
Submit the information on this form via mail to
	<CODE>ics1c@ics.uci.edu</CODE><BR>

<INPUT TYPE=submit VALUE="Do It!">
<INPUT TYPE=reset VALUE="Clear Form">
<P>
<HR>

February 27, 1995 for <A HREF="http://www.ics.uci.edu/~ics1c/">
ICS 1C</a>

</FORM>
</BODY>
</HTML>

